default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mr_cocktail_dev

test:
  <<: *default
  database: mr_cocktail_test
